compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
# fsdp_config:
#   fsdp_auto_wrap_policy: NO_WRAP
#   fsdp_backward_prefetch_policy: BACKWARD_PRE
#   fsdp_forward_prefetch: false
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_offload_params: false
#   fsdp_sharding_strategy: FULL_SHARD
#   fsdp_state_dict_type: SHARDED_STATE_DICT
#   fsdp_sync_module_states: true
#   fsdp_use_orig_params: true
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: 1,2,3,4,5,6,7
machine_rank: 0
mixed_precision: bf16
num_machines: 1
num_processes: 7
